version: "3"

services:
  nlp-service:
    build: .
    volumes:
      - .:/app
    ports:
      - "${NLP_PORT}:${NLP_PORT}"
    command:
      - python -m nlp_service
      - ${NLP_HOST}:${NLP_PORT}
