version: "3"

services:
  cpu:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "50051:50051"
  cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    # volumes:
    #   - .:/app
    ports:
      - "50051:50051"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ["7"]
              capabilities: ["gpu"]
