version: "3"

services:
  nlp-service:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ["7"]
              capabilities: ["gpu"]
