version: "3"

services:
  nlp-service:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    command: poetry run python -m nlp_service ${HOST}:${PORT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ["7"]
              capabilities: ["gpu"]
