[tool.poetry]
name = "NLP"
version = "0.1.0"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.19.5"
scipy = "^1.6.2"
spacy = "^3.0.5"
typer = "^0.3.2"
grpcio = "^1.32"
tensorflow = { version = "^2.4.1", optional = true }
sentence-transformers = { version = "^1.0.4", optional = true }
tensorflow-hub = { version = "^0.11.0", optional = true }
arg-services = "^0.1.4"
# arg-services = { path = "../Schema/python", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
server = ["sentence-transformers", "tensorflow", "tensorflow-hub"]
